### ISSUE TITLE
Package for Unraid 6.10rc4

### ISSUE THREAD

**Issue by iiseppi** [Stonyx/QNAP-EC#2]
Possible to make package for Unraid 6.10 ?

**Comment by Stonyx** [comment]
I no longer run an Unraid system but I'll try to post the full instructions used to build the Unraid packages.

**Comment by gotens87** [comment]
The same dev who puts out nvidia, zfs and other important unRAID plugins has offered to place this driver as an optional plugin for QNAP device, this will mean it could be available automatically shortly after every OS update. They were concerned about the stale development of the driver but I don't know if that's just because there is nothing really left to do. It works fine on my TS-873A.

**Comment by Stonyx** [comment]
I think I know who you're referring to.  That would be great if he adds it to his list of items.  The development stopped purely because there's nothing left to develop.  If any bugs are discovered or new features requested (assuming they are possible ... we're limited by what functionality QNAP exposes in their binary) development will continue.

**Comment by ich777** [comment]
@Stonyx I think you are talking about me... 😆 
Can you maybe give me a list of Qnap NAS systems that will be supported with this specific "driver" or is it only the TS-873A one or is this not known with which systems it's compatible?
If I create a plugin, I want to be sure to have a proper README for the driver plugin and also a way to update the plugin to support other Qnap systems without much effort (but I'm not to sure about that, maybe it's better to create individual plugins for different systems).

Another side questions since I've not taken a look at this long time, does you `Makefile` support `DESTDIR`?
From what I remember I copy over the three files that are compiled over manually...
It would be really great if it supports `DESTDIR` because I then not have to copy it over manually but it works the way I do it now too... 😄

**Comment by Stonyx** [comment]
A little background on how the driver works should hopefully answer two of your questions.  Originally we looked into reverse engineering how the QNAP software communicates with the IT8528 chip (that controls and reads fan speeds and temperatures in many different units) but it proved significant more reliable to leverage one of the actual QNAP binaries and communicate with that binary (which in turn communicates with the chip) instead of the chip directly.  That means the driver supports any QNAP unit that that binary supports in its EC mode.  So far that seems to be only the IT8528 chip which is found in quite a few different units.  The ones that we're aware of include:

TS-473A
TS-673A
TS-873A
TS-453Be
TS-877

But it's a common chip so likely there are significantly more models that this driver will work on but we just haven't come across such reports or have any documentation on which chip they actually contain.  By default the driver will check for the presence of the IT8528 chip but that can be disabled to load the driver on systems with other chips to check if they might be supported by the binary.

The makefile does support DESTDIR.  And the QNAP binary is needed.  The one included has been taken from the TS-x73A firmware and seems to work on other models but technically for best compatibility the binary should be taken from the firmware of the unit that this driver will actually run on.

Hope that helps a little with your plans.  Let me know if you need anything else clarified, etc.

**Comment by iiseppi** [comment]
Thank you all! I have Qnap TS-h886, but cannot say is the IT8528 chip in this nas. Is there way to check it out from nas?

**Comment by ich777** [comment]
@Stonyx thank you for the clarifications!

I will try to compile it tomorrow and add it to my build toolchain and create a very simple plugin for now, I will of course mention the five listed units that you've mentioned and also link the GitHub repo as always in my plugins.

Maybe another short question, after installing the modules and doing the modprobe, is it also needed to load up qnap-ec once or does it need to run in the background or is that up to the user?

**Comment by Stonyx** [comment]
The driver invokes the QNAP binary automagically as needed so after running modprobe there's nothing else needed.  Whenever any application reads the various sensors available on the system they will also read the sensors exposed by this driver.  For example, you can use the sensors tool from the lm_sensors package to read all the sensors in the system.

**Comment by Stonyx** [comment]
@ich777 Found a couple more QNAP models that apparently use the IT8528 chip and therefore would be supported by this driver:

TS-1677x
TS-253B

**Comment by ich777** [comment]
@Stonyx & @iiseppi & @gotens87 plugin is basically done, please try it on your systems (please keep in mind you have to be on Unraid 6.10.2):

`https://raw.githubusercontent.com/ich777/unraid-qnapec/master/qnap-ec.plg`

I'm waiting with the release until your responses if it is actually working.

**Comment by ich777** [comment]
FYI @Stonyx plugin is released and it works as expected from the tests that @gotens87 did.

Hope that's ok for you @Stonyx:

![image](https://user-images.githubusercontent.com/28066518/171149249-fb43843f-c8e5-498d-bb38-e2463fa1ebe3.png)

![image](https://user-images.githubusercontent.com/28066518/171149293-0a5c50bd-efa2-4fe1-b882-b945bd90441f.png)


@iiseppi can you also test if it works on your unit?

**Comment by ich777** [comment]
@iiseppi have you been able to test it yet?

**Comment by iiseppi** [comment]
I’m sorry, but I had to restore original qnap os to device and ordered new pc parts to coming to my new unraid server and after that I can test it.

**Comment by ich777** [comment]
@iiseppi can this issue be closed? I think most users have no issues with 6.10.0+ and this module on unRAID.

**Comment by iiseppi** [comment]
Hello,

Yes, U can close the issue, all working. Thx!

**Comment by ich777** [comment]
@iiseppi I think you have to close this issue since you've created it... ;)

**Comment by iiseppi** [comment]
_"Crawling under the rock...."_ ;) :D
