### ISSUE TITLE
Syslog Output

### ISSUE THREAD

**Issue by superschlundi** [Stonyx/QNAP-EC#5]
Hello, 

i am using the qnap-ec plugin on Unraid via @ich777 's community plugin on a QNAP TS-453be. It works fine an I am able to control the fan. 

But I recognized that the plugin has a very chatty output and is reporting an error every time the fan speed is changed: 

`Aug 19 08:49:44 QUBE qnap-ec[27142]: calling ec_sys_set_fan_speed function with 0 and 64 arguments
Aug 19 08:49:44 QUBE qnap-ec[27142]: unexpected call to simulated Ini_Conf_Get_Field_Int function
Aug 19 08:49:44 QUBE qnap-ec[27142]: function ec_sys_set_fan_speed returned 0
Aug 19 08:49:49 QUBE autofan: Highest disk temp is 36C, adjusting fan speed from: OFF (0% @ 0rpm) to: 64 (25% @ 638rpm)`

Since this behavior is spamming into the syslog I would consider it as an issue. 

The TS-453be is running on the latest BIOS, behavior is present when BIOS fan setting is set to "manual" or to "auto".

**Comment by scottshanafelt** [comment]
Yes I noticed this as well.  Would be great to squash non-error logging.  My fan monitoring script adjusts the fan every 5 seconds, so it’s a ton of log noise.

Scott

**Comment by ich777** [comment]
@fl0bit & @scottshanafelt since @Stonyx hasn't responded yet I give you here a workaround...

To hide this messages, create the following lines in your `go` file (you have to reboot afterwards):

```
# Hide QNAP-EC error messages
echo ":msg,contains,\"calling ec_sys_set_fan_speed function with\" stop" >> /etc/rsyslog.d/01-blocklist.conf
echo ":msg,contains,\"unexpected call to simulated Ini_Conf_Get_Field_Int function\" stop" >> /etc/rsyslog.d/01-blocklist.conf
echo ":msg,contains,\"function ec_sys_set_fan_speed returned\" stop" >> /etc/rsyslog.d/01-blocklist.conf
/etc/rc.d/rc.rsyslogd restart
```

You can also hide the autofan message by adding the before the `/etc/rc.d/rc.rsyslogd restart`:
`echo ":msg,contains,\"autofan: Highest disk temp is\" stop" >> /etc/rsyslog.d/01-blocklist.conf`

Please report back if this is also working for you.

**Comment by fl0bit** [comment]
Thanks @ich777 , that's what I did anyway! 

Maybe useful for some: 

I decided to use `fancontrol` instead of the dynamix fan control plugin, since it allows me to control the fan speed based on cpu temps. In my TS-453Be the drive temps are fine, even with minimal fan speed of 500rpm (Stock Fan replaced by BeQuiet Shadow Wing anyway), but the cpu definitely needs some more cooling under load. 

To get a fan profile you have to run `pwmconfig` once and save the config file on your preferred path. Mine is saved under /boot/config/fancontrol

Under /boot/config/go you must start fancontrol with the path to your config file of course: 

```
#fancontrol
fancontrol /boot/config/fan control
```

Now I am happy with a almost totally quiet Unraid-driven QNAP Device :)

**Comment by Stonyx** [comment]
Thanks for bringing this to our attention.  Looks like two out of the three messages you listed are debugging left overs.  I'll try to get those removed as soon as I can turn my attention to this project.  The third message (unexpected call ...) is actually an error message.  I might increase the details in that error message so that we can figure out what's causing it (I have a feeling it's not actually an error but we'll need more details to figure out how the code needs to be changed to deal with this unexpected situation).  I'll post back once the changes are done, etc.

**Comment by ich777** [comment]
@Stonyx please keep me up to date since I will build test packages for Unraid for both of them.

**Comment by Stonyx** [comment]
@ich777 I've removed the left over logging and added more logging to the "error" message so that we can determine if it's actually an error (almost 100% sure it's not) or how to change the code to not flag this unexpected call as an error.  That means there will most likely still be one syslog entry every time the fan speed is changed.

@superschlundi and @scottshanafelt, once you are running the latest version of the driver, please post the one syslog entry that you'll most likely continue to get so that we can get to the bottom of this and completely eliminate these messages.

**Comment by ich777** [comment]
@superschlundi & @scottshanafelt can you tell me on what Unraid version are you since I need to build the package for your specific Unraid version.

@Stonyx would it be maybe possible to add a Kernel module option to suppress this messages entirely?

**Comment by superschlundi** [comment]
@ich777 i am running the latest stable 6.10.3 release

**Comment by scottshanafelt** [comment]
Hi, I am running 6.10.3

Thank you!

**Comment by ich777** [comment]
@superschlundi & @scottshanafelt I've attached a zip file for 6.10.3 (had to zip the files because GitHub doesn't allow uploads of `txz` and `md5` files...)
This zip file containers the two necessary files (.txz & .md5) which need to go in your `/boot/config/plugins/qnap-ec/packages/5.15.46/` folder (please delete the "old" two files in the first place) and reboot your server after you've inserted them into there.

[qnapec-20220826-5.15.46-Unraid-1.zip](https://github.com/Stonyx/QNAP-EC/files/9436144/qnapec-20220826-5.15.46-Unraid-1.zip)

**Comment by scottshanafelt** [comment]
You are awesome, thank you so much

Scott

**Comment by superschlundi** [comment]
@ich777 thanks a lot! 
@Stonyx : 
Now i get only one message every time fancontrol is changing the fan speed like this: 
`Aug 26 22:25:06 QUBE qnap-ec[15098]: unexpected call to simulated Ini_Conf_Get_Field_Int function with /etc/model.conf, System Enclosure, and MAX_CPU_FAN_NUM arguments `

I hope that’s helpful for the problem.

**Comment by Stonyx** [comment]
@superschlundi that's the output we needed.  Turns out this was a copy/paste bug in the code.  It has now been fixed and the driver version was updated to 1.1.2.  Once @ich777 has a chance to add this latest version into his plugin you'll be all good to go with no more syslog spamming.  Thanks for bringing this to our attention.

**Comment by ich777** [comment]
@superschlundi & @scottshanafelt I have rebuilt the packages for Unraid stable (6.10.3) and next (6.11.0-rc4), please uninstall the plugin, reinstall it from the CA App and then reboot your server.

Thank you @Stonyx for the quick fix!

**Comment by superschlundi** [comment]
@ich777 Awesome! Everything is working fine now on my system, no log output from qnap-ec so far! 
@Stonyx Thanks for the quick fix too! 

I would wait for @scottshanafelt result before closing the issue.

**Comment by scottshanafelt** [comment]
Hi,

Sorry for being pokey.  I just updated QNAP-EC and rebooted and the logging issue seems resolved!

Thank you all so much for your help!  I love this community

Scott
