### ISSUE TITLE
How can I make this run for TS-473A?

### ISSUE THREAD

**Issue by k-matti** [Stonyx/QNAP-EC#7]
Hi,

I have TS-473A with OMV6 (Debian). How can I make this script running for my Qnap? Where can I find this file: libuLinux_hal.so?

I have found that libuLinux_hal.so is exactly the same for 873a as 473a. I have successfully build and install this library but I don't know how to use it under Debian to automatically set fans speed.

**Comment by Stonyx** [comment]
Sorry for the late response.  The libuLinux_hal.so file is part of the original QNAP OS firmware.  It can be a pain to get but as you found out it's identical for all TS-X73A series units.

QNAP-EC exposes the hardware fan sensors to the OS so that it can read the fan speeds as well as change them.  But you still need something to actually monitor and change those fan speeds.  There are several utilities available for pretty much every Linux distro out there.  The most common one is fancontrol which is usually part of the lm-sensors package.  You would use that utility in conjunction with QNAP-EC to actually monitor and control your fans.

BTW, my personal favorite utility to monitor and control the fans on a NAS is https://github.com/desbma/hddfancontrol
