### ISSUE TITLE
Make file fails on TrueNAS-SCALE-22.12.0

### ISSUE THREAD

**Issue by marleyjaffe** [Stonyx/QNAP-EC#9]
I am unable to successfully run the `make install` command although after the `modprobe` command does run without issue. After running these commands, my fans are still running at 100%. Do I need to manually install the fancontrol package on the OS as well to take advantage of this driver? This is for a fresh conversion of a QNap TS-EC2480U-RP  to TrueNas, I believe can reinstall the QNap OS to get the libuLinux_hal.so file but where does this file exist/how do I find it if I reinstall the QNAP OS. Thanks for any thoughts!

```
Linux truenas 5.15.79+truenas

admin@truenas[~/QNAP-EC]# sudo make install
rm -f qnap-ec
make -C /lib/modules/5.15.79+truenas/build M=/home/admin/QNAP-EC clean
make[1]: Entering directory '/usr/src/linux-headers-5.15.79+truenas'
make[1]: Leaving directory '/usr/src/linux-headers-5.15.79+truenas'
cc -o qnap-ec qnap-ec-helper.c -Wall -O2 -export-dynamic -ldl
make -C /lib/modules/5.15.79+truenas/build M=/home/admin/QNAP-EC MODULE_CFLAGS= modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.79+truenas'
  CC [M]  /home/admin/QNAP-EC/qnap-ec.o
  MODPOST /home/admin/QNAP-EC/Module.symvers
  CC [M]  /home/admin/QNAP-EC/qnap-ec.mod.o
  LD [M]  /home/admin/QNAP-EC/qnap-ec.ko
  BTF [M] /home/admin/QNAP-EC/qnap-ec.ko
Skipping BTF generation for /home/admin/QNAP-EC/qnap-ec.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.79+truenas'
/bin/install --owner=root --group=root --mode=644 libuLinux_hal.so \
  /usr/local/lib/libuLinux_hal.so
/bin/install --strip --owner=root --group=root --mode=755 qnap-ec \
  /usr/local/sbin/qnap-ec
make -C /lib/modules/5.15.79+truenas/build M=/home/admin/QNAP-EC modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.15.79+truenas'
arch/x86/Makefile:142: CONFIG_X86_X32 enabled but no binutils support
  INSTALL /lib/modules/5.15.79+truenas/extra/qnap-ec.ko
  DEPMOD  /lib/modules/5.15.79+truenas
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.15.79+truenas'
/sbin/depmod --quick
/sbin/modprobe qnap-ec
modprobe: ERROR: could not insert 'qnap_ec': No such device
make: [Makefile:90: install] Error 1 (ignored)
admin@truenas[~/QNAP-EC]# sudo modprobe qnap-ec check-for-chip=no
admin@truenas[~/QNAP-EC]# 

```

**Comment by Stonyx** [comment]
It looks like the main issue is that this unit most likely doesn't use an IT8528 E.C. chip.  This line in the output your provided:
`modprobe: ERROR: could not insert 'qnap_ec': No such device`
tells us that when the driver was being inserted into the kernel it errored out because the device this driver is designed for wasn't found (unfortunately the error messages that can be shown during this step are preset and very limited).

You can force the driver to run by manually inserting it with this command:
`sudo modprobe qnap-ec check-for-chip=no`
but that means the driver will bypass sanity checks designed to look for the correct chip and just try to do its thing whether it thinks there's a chip there to communicate with or not, which I see you did.  You would then want to run a utility like fancontrol for example (which you'll need to install) to actually monitor the fans and control them.  If that fails to control the fans then even though we forced the driver to load there clearly isn't a chip to actually communicate with to control the fans.

**Comment by marleyjaffe** [comment]
What you've said makes sense. I'll work to install fancontrol and see if I get any positive response. Based on your experience, if that does not work is there any next step other than relying on the QNAP OS for working fan control?
